"""Domain ontology snippets for keyword-based detection."""

DOMAIN_ONTOLOGIES = {
    "TECHNOLOGY": {
        "keywords": [
            "software",
            "api",
            "algorithm",
            "code",
            "framework",
            "database",
            "programming",
            "developer",
            "system",
            "server",
            "cloud",
            "kubernetes",
            "docker",
            "microservices",
            "machine learning",
            "ai",
            "neural",
            "python",
            "javascript",
            "java",
            "react",
            "node",
            "aws",
            "azure",
        ],
        "description": "Technology and software-related content",
        "entity_types": [
            "Software",
            "API",
            "Framework",
            "Database",
            "Service",
            "Model",
        ],
    },
    "FINANCIAL": {
        "keywords": [
            "revenue",
            "profit",
            "investment",
            "stock",
            "market",
            "banking",
            "financial",
            "equity",
            "capital",
            "portfolio",
            "trading",
            "asset",
            "fund",
            "dividend",
            "quarterly",
            "earnings",
            "上市",
            "股价",
        ],
        "description": "Financial and business content",
        "entity_types": ["Company", "Stock", "Market", "Currency", "Investment"],
    },
    "MEDICAL": {
        "keywords": [
            "disease",
            "treatment",
            "drug",
            "patient",
            "symptom",
            "diagnosis",
            "clinical",
            "pharmaceutical",
            "therapy",
            "health",
            "medical",
            "医院",
            "药物",
            "临床",
            "患者",
            "症状",
            "治疗",
        ],
        "description": "Medical and healthcare content",
        "entity_types": ["Disease", "Drug", "Treatment", "Symptom", "Anatomy"],
    },
    "LEGAL": {
        "keywords": [
            "law",
            "legal",
            "contract",
            "regulation",
            "court",
            "compliance",
            "liability",
            "agreement",
            "intellectual property",
            "patent",
            "律师",
            "合同",
            "法规",
            "诉讼",
        ],
        "description": "Legal and regulatory content",
        "entity_types": ["Law", "Contract", "Regulation", "Court", "Party"],
    },
    "SCIENTIFIC": {
        "keywords": [
            "research",
            "study",
            "hypothesis",
            "experiment",
            "data",
            "analysis",
            "hypothesis",
            "methodology",
            "peer review",
            "journal",
            "论文",
            "研究",
        ],
        "description": "Scientific research content",
        "entity_types": ["Study", "Hypothesis", "Method", "Finding"],
    },
}
