"""Domain ontology snippets for keyword-based detection.

Updated with comprehensive cryptocurrency domain ontologies for 2026.
"""

DOMAIN_ONTOLOGIES = {
    # ============================================================================
    # CRYPTOCURRENCY DOMAINS
    # ============================================================================
    "BITCOIN": {
        "keywords": [
            # Core Bitcoin terms
            "bitcoin",
            "btc",
            "satoshi",
            "sats",
            "satoshi nakamoto",
            "bitcoin protocol",
            "bitcoin network",
            "mainnet",
            # Monetary aspects
            "digital gold",
            "store of value",
            "sound money",
            "21 million",
            "scarcity",
            "fixed supply",
            "deflationary",
            "monetary policy",
            "disinflationary",
            # Mining & consensus
            "mining",
            "miner",
            "mining pool",
            "hash rate",
            "hashrate",
            "proof of work",
            "pow",
            "difficulty adjustment",
            "block reward",
            "coinbase reward",
            "halving",
            "2024 halving",
            "2028 halving",
            "block subsidy",
            "asic",
            "mining rig",
            "antminer",
            "energy consumption",
            "sustainable mining",
            "renewable mining",
            # Technical
            "blockchain",
            "block",
            "transaction",
            "confirmation",
            "mempool",
            "fee rate",
            "sats per byte",
            "transaction fee",
            "segwit",
            "taproot",
            "schnorr signatures",
            "bech32",
            "utxo",
            "unspent transaction output",
            "coin control",
            "full node",
            "light client",
            "spv",
            "bitcoin core",
            "bip",
            "bitcoin improvement proposal",
            "soft fork",
            "hard fork",
            "activation",
            # Scaling
            "lightning network",
            "ln",
            "payment channel",
            "rgb protocol",
            "omnibolt",
            "state chains",
            "sidechain",
            "liquid network",
            "rootstock",
            "rsk",
            "fedimint",
            "ecash",
            "cashu",
            # Institutional
            "bitcoin etf",
            "spot etf",
            "futures etf",
            "strategy",
            "michael saylor",
            "microstrategy",
            "digital asset treasury",
            "dat",
            "nation state adoption",
            "sovereign wealth fund",
            "bitcoin reserve",
            "strategic bitcoin reserve",
            "corporate treasury",
            "bitcoin standard",
            # Markets
            "bitcoin dominance",
            "btc dominance",
            "btcd",
            "realized price",
            "mvrv",
            "nupl",
            "hodl waves",
            "long term holder",
            "short term holder",
            "lth",
            "sth",
            "accumulation",
            "distribution",
            "capitulation",
            "fear and greed index",
            "bitcoin volatility",
            # History & culture
            "genesis block",
            "pizza day",
            "mt gox",
            "silk road",
            "blocksize war",
            "big block",
            "small block",
            "bitcoin cash",
            "bch",
            "bitcoin sv",
            "bsv",
            "cypherpunk",
            "cryptography",
            "libertarian",
            "hodl",
            "not your keys",
            "stack sats",
        ],
        "description": "Bitcoin-specific knowledge including protocol, mining, institutional adoption",
        "entity_types": [
            "Bitcoin",
            "Satoshi",
            "MiningPool",
            "BitcoinUpgrade",
            "LightningNode",
            "BitcoinETF",
            "DigitalAssetTreasury",
            "BitcoinAnalyst",
            "BitcoinDeveloper",
            "NationState",
        ],
        "relationship_types": [
            "MINES",
            "HOLDS",
            "OPERATES",
            "ISSUES",
            "BACKS",
            "UPGRADED_TO",
            "BUILDS_ON",
            "ADOPTED_BY",
        ],
    },
    "INSTITUTIONAL_CRYPTO": {
        "keywords": [
            # ETFs & ETPs
            "exchange traded fund",
            "etf",
            "etp",
            "spot bitcoin etf",
            "spot ethereum etf",
            "ibit",
            "gbtc",
            "fbtc",
            "arkb",
            "bito",
            "blackrock",
            "ishares",
            "grayscale",
            "fidelity",
            "vaneck",
            "ark invest",
            "bitwise",
            "wisdomtree",
            "invesco",
            "vanguard",
            "charles schwab",
            "in-kind redemption",
            "cash redemption",
            "creation basket",
            "redemption basket",
            "net asset value",
            "nav",
            "premium",
            "discount",
            "expense ratio",
            "management fee",
            "authorized participant",
            "ap",
            "market maker",
            "liquidity provider",
            # Custody
            "custody",
            "custodian",
            "qualified custodian",
            "cold storage",
            "multi-sig",
            "multi-signature",
            "bitgo",
            "coinbase custody",
            "fidelity digital assets",
            "bny mellon",
            "state street",
            "jpmorgan",
            "copper",
            "anchorage",
            "fireblocks",
            "soc 2",
            "soc 1",
            "type ii audit",
            "insurance coverage",
            "lloyd's of london",
            # Treasury & Corporate
            "digital asset treasury",
            "dat",
            "bitcoin treasury",
            "crypto treasury",
            "strategy",
            "microstrategy",
            "michael saylor",
            "tesla bitcoin",
            "square bitcoin",
            "block bitcoin",
            "metaplanet",
            "semler scientific",
            "treasury reserve asset",
            "tra",
            "bitcoin accumulation",
            "dollar cost averaging",
            "convertible bond",
            "at the market offering",
            # Investment Vehicles
            "crypto hedge fund",
            "crypto venture fund",
            "pantera capital",
            "a16z crypto",
            "paradigm",
            "multicoin capital",
            "polychain capital",
            "digital currency group",
            "dcg",
            "grayscale trust",
            "otc trust",
            "closed end fund",
            "cef",
            "interval fund",
            "40 act fund",
            "qualified purchaser",
            "accredited investor",
            # 401(k) & Retirement
            "401(k)",
            "retirement account",
            "ira",
            "self-directed ira",
            "solo 401(k)",
            "department of labor",
            "dol",
            "plan sponsor",
            "fiduciary",
            "forusall",
            "bitcoin 401k",
            # Institutional Metrics
            "assets under management",
            "aum",
            "inflow",
            "outflow",
            "flow",
            "cost basis",
            "average entry",
            "institutional adoption",
            "allocation",
            "endowment",
            "pension fund",
            "sovereign wealth",
        ],
        "description": "Institutional cryptocurrency adoption including ETFs, custody, treasuries",
        "entity_types": [
            "ETFIssuer",
            "CryptoETF",
            "CryptoCustodian",
            "DigitalAssetTreasury",
            "CryptoFund",
            "InstitutionalInvestor",
            "PlanSponsor",
            "AuthorizedParticipant",
        ],
        "relationship_types": [
            "ISSUES",
            "MANAGES",
            "CUSTODIES",
            "HOLDS",
            "INVESTS_IN",
            "PARTICIPATES_IN",
            "PROVIDES_LIQUIDITY",
        ],
    },
    "DEFI": {
        "keywords": [
            # General
            "decentralized finance",
            "defi",
            "open finance",
            "permissionless",
            "trustless",
            "non-custodial",
            "smart contract",
            "protocol",
            "dao",
            "tvl",
            "total value locked",
            "mcap",
            "market cap",
            "fdv",
            "fully diluted valuation",
            "apy",
            "apr",
            "yield",
            "return",
            "impermanent loss",
            "il",
            "gas fee",
            "transaction cost",
            # Lending
            "lending protocol",
            "borrowing",
            "lending",
            "aave",
            "compound",
            "morpho",
            "maple finance",
            "radiant",
            "venus",
            "justlend",
            "collateral",
            "collateral ratio",
            "ltv",
            "liquidation",
            "health factor",
            "flash loan",
            "uncollateralized loan",
            "overcollateralized",
            "undercollateralized",
            "isolated lending",
            "cross-collateral",
            "interest rate model",
            "utilization rate",
            "supply apy",
            "borrow apy",
            "credit market",
            "debt market",
            # DEXs
            "decentralized exchange",
            "dex",
            "uniswap",
            "pancakeswap",
            "sushiswap",
            "curve",
            "balancer",
            "bancor",
            "1inch",
            "matcha",
            "paraswap",
            "amm",
            "automated market maker",
            "constant product",
            "x*y=k",
            "concentrated liquidity",
            "v3",
            "range order",
            "tick",
            "liquidity pool",
            "lp",
            "lp token",
            "liquidity provider",
            "yield farmer",
            "slippage",
            "price impact",
            "constant sum",
            "stableswap",
            "orderbook dex",
            "order book",
            "limit order",
            "market order",
            "hybrid dex",
            "amm aggregator",
            # Derivatives
            "perpetual",
            "perp",
            "perpetual futures",
            "dydx",
            "gmx",
            "hyperliquid",
            "gains network",
            "funding rate",
            "index price",
            "mark price",
            "margin trading",
            "isolated margin",
            "cross margin",
            "liquidation price",
            "maintenance margin",
            "open interest",
            "oi",
            "options protocol",
            "opyn",
            "lyra",
            "premia",
            "structured product",
            "ribbon",
            "thetanuts",
            "delta neutral",
            "market neutral",
            # Yield
            "yield farming",
            "liquidity mining",
            "vault",
            "yearn",
            "convex",
            "boosted yield",
            "native yield",
            "restaking",
            "eigenlayer",
            "pendle",
            "liquid staking",
            "lido",
            "rocket pool",
            "staking derivative",
            "lst",
            "lsd",
            "real yield",
            "protocol revenue",
            "yield aggregator",
            "yield optimizer",
            # Bridges
            "bridge",
            "cross chain",
            "layerzero",
            "wormhole",
            "axelar",
            "multichain",
            "stargate",
            "across",
            "wrapped token",
            "wbtc",
            "weth",
            "canonical bridge",
            "native bridge",
            "lock and mint",
            "burn and mint",
            # Oracles
            "oracle",
            "chainlink",
            "link",
            "price feed",
            "data feed",
            "pyth",
            "api3",
            "band protocol",
            "oracle manipulation",
            "flash loan attack",
        ],
        "description": "Decentralized finance protocols including lending, DEXs, yield farming",
        "entity_types": [
            "DeFiProtocol",
            "DEX",
            "LendingProtocol",
            "DerivativesProtocol",
            "YieldAggregator",
            "Bridge",
            "Oracle",
            "SmartContract",
            "LiquidityPool",
            "GovernanceToken",
        ],
        "relationship_types": [
            "LENDS",
            "BORROWS",
            "PROVIDES_LIQUIDITY",
            "SWAPS",
            "STAKES",
            "GOVERNS",
            "BRIDGES_TO",
            "FEEDS_PRICE",
            "COLLATERALIZES",
        ],
    },
    "STABLECOINS": {
        "keywords": [
            # Types
            "stablecoin",
            "stable coin",
            "fiat backed",
            "fiat collateralized",
            "crypto collateralized",
            "over collateralized",
            "algorithmic stablecoin",
            "algo stable",
            "commodity backed",
            "gold backed",
            "synthetic dollar",
            # Major Stablecoins
            "tether",
            "usdt",
            "usd coin",
            "usdc",
            "circle",
            "binance usd",
            "busd",
            "dai",
            "makerdao",
            "maker",
            "paypal usd",
            "pyusd",
            "first digital usd",
            "fdusd",
            "trueusd",
            "tusd",
            "pax dollar",
            "usdp",
            "gemini dollar",
            "gusd",
            "liquity usd",
            "lusd",
            "frax",
            "frax usd",
            "ethena",
            "usde",
            "synthetic dollar",
            # Mechanics
            "peg",
            "depeg",
            "repeg",
            "collateral ratio",
            "cr",
            "redemption",
            "mint",
            "burn",
            "attestation",
            "proof of reserves",
            "reserve composition",
            "treasury holdings",
            "yield bearing stablecoin",
            "interest bearing",
            # GENIUS Act Terms
            "genius act",
            "payment stablecoin",
            "qualified payment stablecoin",
            "permitted payment stablecoin issuer",
            "nonbank issuer",
            "bank issuer",
            "1:1 reserve",
            "reserve requirements",
            "monthly disclosure",
            "quarterly audit",
            "redemption rights",
            "same day redemption",
            # Use Cases
            "remittance",
            "cross border payment",
            "settlement",
            "trading pair",
            "quote currency",
            "base currency",
            "collateral",
            "margin",
            "yield farming",
            "lending",
            "treasury management",
            "cash equivalent",
            "offshore dollar",
            "eurodollar",
            # Market Data
            "supply",
            "circulating supply",
            "market cap",
            "dominance",
            "transfer volume",
            "transaction count",
            "active addresses",
            "velocity",
            "premium",
            "discount",
            "basis",
            "curve pool",
            "3pool",
            "lusd pool",
            "liquidity fragmentation",
        ],
        "description": "Stablecoin-specific knowledge including mechanics, regulation, markets",
        "entity_types": [
            "Stablecoin",
            "StablecoinIssuer",
            "ReserveAsset",
            "PaymentCorridor",
            "RedemptionMechanism",
        ],
        "relationship_types": [
            "ISSUES",
            "BACKS",
            "COLLATERALIZES",
            "FACILITATES",
            "PEGS_TO",
            "REDEEMS",
        ],
    },
    "CRYPTO_REGULATION": {
        "keywords": [
            # US Regulators
            "securities and exchange commission",
            "sec",
            "commodity futures trading commission",
            "cftc",
            "financial crimes enforcement network",
            "fincen",
            "office of the comptroller of the currency",
            "occ",
            "federal reserve",
            "fed",
            "department of justice",
            "doj",
            "internal revenue service",
            "irs",
            "department of treasury",
            "treasury",
            "gary gensler",
            "rostin behnam",
            "hester peirce",
            "mark uyeda",
            "paul atkins",
            # International
            "financial action task force",
            "fatf",
            "european union",
            "eu",
            "mica",
            "markets in crypto assets",
            "esma",
            "eba",
            "united kingdom",
            "fca",
            "singapore",
            "mas",
            "hong kong",
            "sfc",
            "japan",
            "fsa",
            "switzerland",
            "finma",
            "dubai",
            "vara",
            # Key Regulations
            "securities act",
            "securities exchange act",
            "commodity exchange act",
            "cea",
            "bank secrecy act",
            "bsa",
            "howey test",
            "reves test",
            "investment company act",
            "40 act",
            "investment advisers act",
            "sarbanes oxley",
            "sox",
            "patriot act",
            "dodd frank",
            # 2025-2026 Specific
            "genius act",
            "stablecoin regulation",
            "clarity act",
            "financial innovation",
            "market structure legislation",
            "sab 121",
            "staff accounting bulletin",
            "digital asset framework",
            "fit21",
            "financial innovation",
            "responsible financial innovation act",
            # Enforcement & Compliance
            "enforcement action",
            "settlement",
            "no action letter",
            "safe harbor",
            "regulation by enforcement",
            "compliance program",
            "aml",
            "kyc",
            "know your customer",
            "customer identification",
            "suspicious activity report",
            "sar",
            "travel rule",
            "beneficial ownership",
            "sanctions",
            "ofac",
            "tornado cash",
            "securities fraud",
            "market manipulation",
            "insider trading",
            "wash trading",
            "unregistered securities",
            "broker dealer",
            "bd",
            "transfer agent",
            "clearing agency",
            "alternative trading system",
            "ats",
            # Legal Cases
            "sec v ripple",
            "sec v coinbase",
            "sec v binance",
            "sec v kraken",
            "sec v uniswap",
            "sec v consensys",
            "lbry",
            "telegram",
            "kik",
            "terraform labs",
            "do kwon",
            "ftx",
            "sbf",
            "sam bankman fried",
            "celsius",
            "voyager",
            "blockfi",
        ],
        "description": "Cryptocurrency regulation including SEC, CFTC, international frameworks",
        "entity_types": [
            "RegulatoryBody",
            "Regulation",
            "LegalCase",
            "ComplianceFramework",
            "EnforcementAction",
            "Legislation",
            "Regulator",
        ],
        "relationship_types": [
            "REGULATES",
            "ENFORCES",
            "COMPLIES_WITH",
            "CHALLENGES",
            "DEFINES",
            "AMENDS",
        ],
    },
    "BLOCKCHAIN_INFRA": {
        "keywords": [
            # Layer 1s
            "layer 1",
            "l1",
            "base layer",
            "ethereum",
            "eth",
            "solana",
            "sol",
            "avalanche",
            "avax",
            "cardano",
            "ada",
            "polkadot",
            "dot",
            "cosmos",
            "atom",
            "near protocol",
            "near",
            "aptos",
            "sui",
            "monad",
            "tron",
            "trx",
            "bnb chain",
            "binance smart chain",
            "bsc",
            "fantom",
            "ftm",
            "polygon",
            "matic",
            "arbitrum",
            "optimism",
            "base",
            # Consensus
            "proof of work",
            "pow",
            "proof of stake",
            "pos",
            "delegated proof of stake",
            "dpos",
            "proof of authority",
            "poa",
            "proof of history",
            "poh",
            "byzantine fault tolerance",
            "bft",
            "tendermint",
            "hotstuff",
            "validator",
            "validator set",
            "block producer",
            "slot leader",
            "finality",
            "probabilistic finality",
            "epoch",
            "slot",
            "era",
            "attestation",
            "committee",
            "slashing",
            "jailing",
            "unbonding period",
            "warmup",
            # Scaling
            "layer 2",
            "l2",
            "rollup",
            "rollups",
            "optimistic rollup",
            "zero knowledge rollup",
            "zk rollup",
            "validity rollup",
            "sequencer",
            "proposer",
            "data availability",
            "da",
            "data availability sampling",
            "das",
            "eigenlayer",
            "celestia",
            "avail",
            "near da",
            "settlement layer",
            "execution layer",
            "sharding",
            "danksharding",
            "proto danksharding",
            "eip 4844",
            "blob",
            "state channel",
            "payment channel",
            "sidechain",
            "validium",
            "volition",
            "starkex",
            # Cross-chain
            "interoperability",
            "cross chain",
            "bridge",
            "bridging",
            "atomic swap",
            "htlc",
            "ibc",
            "inter blockchain communication",
            "polkadot xcm",
            "xcm",
            "layerzero",
            "omnichain",
            "wrapped asset",
            "canonical bridge",
            "native bridge",
            "third party bridge",
            "bridge hack",
            "bridge exploit",
            "lock and mint",
            "burn and mint",
            "liquidity network",
            "bridge aggregation",
            # MEV
            "mev",
            "maximal extractable value",
            "miner extractable value",
            "sandwich attack",
            "frontrunning",
            "backrunning",
            "arbitrage",
            "liquidation",
            "searcher",
            "builder",
            "proposer builder separation",
            "pbs",
            "mempool",
            "dark forest",
            "flashbots",
            "mev boost",
            "mev relay",
            "censorship",
            "priority fee",
            "tip",
            # Cryptography
            "cryptography",
            "cryptographic",
            "public key",
            "private key",
            "elliptic curve",
            "secp256k1",
            "eddsa",
            "bls signature",
            "merkle tree",
            "merkle root",
            "patricia tree",
            "trie",
            "zero knowledge proof",
            "zk proof",
            "zk snark",
            "zk stark",
            "circuit",
            "trusted setup",
            "homomorphic encryption",
            "threshold signature",
            "mpc",
            "multi party computation",
            "quantum resistant",
            "post quantum",
            # Network
            "peer to peer",
            "p2p",
            "gossip protocol",
            "libp2p",
            "node",
            "full node",
            "archive node",
            "pruned node",
            "light client",
            "client",
            "geth",
            "nethermind",
            "besu",
            "erigon",
            "consensus client",
            "execution client",
            "prysm",
            "lighthouse",
            "teku",
            "nimbus",
            "lodestar",
            "rpc",
            "json rpc",
            "websocket",
            "api",
            "endpoint",
        ],
        "description": "Blockchain infrastructure including L1/L2 chains, consensus, scaling",
        "entity_types": [
            "Blockchain",
            "Layer2",
            "ConsensusMechanism",
            "Validator",
            "Bridge",
            "ScalingSolution",
            "CryptographicPrimitive",
            "Node",
            "Client",
        ],
        "relationship_types": [
            "VALIDATES",
            "BUILDS_ON",
            "BRIDGES_TO",
            "SCALES",
            "USES_CONSENSUS",
            "OPERATES",
        ],
    },
    # ============================================================================
    # LEGACY DOMAINS (preserved for backwards compatibility)
    # ============================================================================
    "TECHNOLOGY": {
        "keywords": [
            "software",
            "api",
            "algorithm",
            "code",
            "framework",
            "database",
            "programming",
            "developer",
            "system",
            "server",
            "cloud",
            "kubernetes",
            "docker",
            "microservices",
            "machine learning",
            "ai",
            "neural",
            "python",
            "javascript",
            "java",
            "react",
            "node",
            "aws",
            "azure",
        ],
        "description": "Technology and software-related content",
        "entity_types": [
            "Software",
            "API",
            "Framework",
            "Database",
            "Service",
            "Model",
        ],
    },
    "FINANCIAL": {
        "keywords": [
            "revenue",
            "profit",
            "investment",
            "stock",
            "market",
            "banking",
            "financial",
            "equity",
            "capital",
            "portfolio",
            "trading",
            "asset",
            "fund",
            "dividend",
            "quarterly",
            "earnings",
            "上市",
            "股价",
        ],
        "description": "Financial and business content",
        "entity_types": ["Company", "Stock", "Market", "Currency", "Investment"],
    },
    "MEDICAL": {
        "keywords": [
            "disease",
            "treatment",
            "drug",
            "patient",
            "symptom",
            "diagnosis",
            "clinical",
            "pharmaceutical",
            "therapy",
            "health",
            "medical",
            "医院",
            "药物",
            "临床",
            "患者",
            "症状",
            "治疗",
        ],
        "description": "Medical and healthcare content",
        "entity_types": ["Disease", "Drug", "Treatment", "Symptom", "Anatomy"],
    },
    "LEGAL": {
        "keywords": [
            "law",
            "legal",
            "contract",
            "regulation",
            "court",
            "compliance",
            "liability",
            "agreement",
            "intellectual property",
            "patent",
            "律师",
            "合同",
            "法规",
            "诉讼",
        ],
        "description": "Legal and regulatory content",
        "entity_types": ["Law", "Contract", "Regulation", "Court", "Party"],
    },
    "SCIENTIFIC": {
        "keywords": [
            "research",
            "study",
            "hypothesis",
            "experiment",
            "data",
            "analysis",
            "hypothesis",
            "methodology",
            "peer review",
            "journal",
            "论文",
            "研究",
        ],
        "description": "Scientific research content",
        "entity_types": ["Study", "Hypothesis", "Method", "Finding"],
    },
    "CRYPTO_TRADING": {
        "keywords": [
            "bitcoin",
            "btc",
            "cryptocurrency",
            "crypto",
            "digital currency",
            "trading",
            "investing",
            "investment",
            "portfolio",
            "trader",
            "rsi",
            "relative strength index",
            "macd",
            "moving average convergence divergence",
            "ema",
            "exponential moving average",
            "sma",
            "simple moving average",
            "bollinger bands",
            "fibonacci",
            "retracement",
            "support",
            "resistance",
            "trend",
            "uptrend",
            "downtrend",
            "sideways",
            "consolidation",
            "head and shoulders",
            "double top",
            "double bottom",
            "triangle",
            "wedge",
            "flag",
            "pennant",
            "cup and handle",
            "ascending triangle",
            "descending triangle",
            "symmetrical triangle",
            "bull flag",
            "bear flag",
            "doji",
            "hammer",
            "shooting star",
            "engulfing",
            "morning star",
            "evening star",
            "three white soldiers",
            "three black crows",
            "spinning top",
            "stochastic",
            "stoch rsi",
            "williams %r",
            "cci",
            "commodity channel index",
            "adx",
            "average directional index",
            "parabolic sar",
            "ichimoku",
            "swing trading",
            "day trading",
            "scalping",
            "position trading",
            "momentum trading",
            "breakout trading",
            "mean reversion",
            "arbitrage",
            "limit order",
            "market order",
            "stop loss",
            "take profit",
            "trailing stop",
            "stop limit",
            "oco",
            "one cancels other",
            "iceberg order",
            "market cap",
            "market capitalization",
            "volume",
            "liquidity",
            "volatility",
            "order book",
            "depth",
            "spread",
            "bid",
            "ask",
            "slippage",
            "risk management",
            "position sizing",
            "leverage",
            "margin",
            "liquidation",
            "stop loss",
            "take profit",
            "risk reward ratio",
            "drawdown",
            "satoshi",
            "sats",
            "halving",
            "halving event",
            "difficulty adjustment",
            "hash rate",
            "mining",
            "miner",
            "pool",
            "block reward",
            "fear and greed",
            "fomo",
            "fear of missing out",
            "bear market",
            "bull market",
            "accumulation",
            "distribution",
            "capitulation",
            "euphoria",
            "panic",
            "fundamental analysis",
            "technical analysis",
            "on-chain analysis",
            "sentiment analysis",
            "price action",
            "chart analysis",
            "exchange",
            "binance",
            "coinbase",
            "kraken",
            "bitfinex",
            "futures",
            "perpetual",
            "options",
            "spot",
            "margin",
            "timeframe",
            "1m",
            "5m",
            "15m",
            "1h",
            "4h",
            "1d",
            "1w",
            "1M",
            "candle",
            "candlestick",
            "timeframe analysis",
        ],
        "entity_types": [
            "TechnicalIndicator",
            "ChartPattern",
            "TradingStrategy",
            "MarketCondition",
            "SupportLevel",
            "ResistanceLevel",
            "TradingSignal",
            "RiskManagementRule",
            "TradingSession",
            "OrderType",
            "Exchange",
            "MarketEvent",
        ],
        "relationship_types": [
            "INDICATES",
            "PRECEDES",
            "FOLLOWS",
            "CONFIRMS",
            "REJECTS",
            "PART_OF",
            "GENERATES",
            "REQUIRES",
            "INFLUENCES",
            "CORRELATES_WITH",
        ],
        "extraction_goals": [
            "Identify technical indicators mentioned in the text",
            "Extract chart patterns and their characteristics",
            "Find trading strategies and their components",
            "Detect market conditions and sentiment",
            "Identify support and resistance levels",
            "Extract risk management rules and parameters",
            "Find trading signals and their confidence levels",
            "Identify exchanges and platforms mentioned",
            "Extract order types and their parameters",
            "Find market events and their impact",
        ],
    },
}
