"""Domain ontology snippets for keyword-based detection."""

DOMAIN_ONTOLOGIES = {
    "TECHNOLOGY": {
        "keywords": [
            "software",
            "api",
            "algorithm",
            "code",
            "framework",
            "database",
            "programming",
            "developer",
            "system",
            "server",
            "cloud",
            "kubernetes",
            "docker",
            "microservices",
            "machine learning",
            "ai",
            "neural",
            "python",
            "javascript",
            "java",
            "react",
            "node",
            "aws",
            "azure",
        ],
        "description": "Technology and software-related content",
        "entity_types": [
            "Software",
            "API",
            "Framework",
            "Database",
            "Service",
            "Model",
        ],
    },
    "FINANCIAL": {
        "keywords": [
            "revenue",
            "profit",
            "investment",
            "stock",
            "market",
            "banking",
            "financial",
            "equity",
            "capital",
            "portfolio",
            "trading",
            "asset",
            "fund",
            "dividend",
            "quarterly",
            "earnings",
            "上市",
            "股价",
        ],
        "description": "Financial and business content",
        "entity_types": ["Company", "Stock", "Market", "Currency", "Investment"],
    },
    "MEDICAL": {
        "keywords": [
            "disease",
            "treatment",
            "drug",
            "patient",
            "symptom",
            "diagnosis",
            "clinical",
            "pharmaceutical",
            "therapy",
            "health",
            "medical",
            "医院",
            "药物",
            "临床",
            "患者",
            "症状",
            "治疗",
        ],
        "description": "Medical and healthcare content",
        "entity_types": ["Disease", "Drug", "Treatment", "Symptom", "Anatomy"],
    },
    "LEGAL": {
        "keywords": [
            "law",
            "legal",
            "contract",
            "regulation",
            "court",
            "compliance",
            "liability",
            "agreement",
            "intellectual property",
            "patent",
            "律师",
            "合同",
            "法规",
            "诉讼",
        ],
        "description": "Legal and regulatory content",
        "entity_types": ["Law", "Contract", "Regulation", "Court", "Party"],
    },
    "SCIENTIFIC": {
        "keywords": [
            "research",
            "study",
            "hypothesis",
            "experiment",
            "data",
            "analysis",
            "hypothesis",
            "methodology",
            "peer review",
            "journal",
            "论文",
            "研究",
        ],
        "description": "Scientific research content",
        "entity_types": ["Study", "Hypothesis", "Method", "Finding"],
    },
    "CRYPTO_TRADING": {
        "keywords": [
            "bitcoin",
            "btc",
            "cryptocurrency",
            "crypto",
            "digital currency",
            "trading",
            "investing",
            "investment",
            "portfolio",
            "trader",
            "rsi",
            "relative strength index",
            "macd",
            "moving average convergence divergence",
            "ema",
            "exponential moving average",
            "sma",
            "simple moving average",
            "bollinger bands",
            "fibonacci",
            "retracement",
            "support",
            "resistance",
            "trend",
            "uptrend",
            "downtrend",
            "sideways",
            "consolidation",
            "head and shoulders",
            "double top",
            "double bottom",
            "triangle",
            "wedge",
            "flag",
            "pennant",
            "cup and handle",
            "ascending triangle",
            "descending triangle",
            "symmetrical triangle",
            "bull flag",
            "bear flag",
            "doji",
            "hammer",
            "shooting star",
            "engulfing",
            "morning star",
            "evening star",
            "three white soldiers",
            "three black crows",
            "spinning top",
            "stochastic",
            "stoch rsi",
            "williams %r",
            "cci",
            "commodity channel index",
            "adx",
            "average directional index",
            "parabolic sar",
            "ichimoku",
            "swing trading",
            "day trading",
            "scalping",
            "position trading",
            "momentum trading",
            "breakout trading",
            "mean reversion",
            "arbitrage",
            "limit order",
            "market order",
            "stop loss",
            "take profit",
            "trailing stop",
            "stop limit",
            "oco",
            "one cancels other",
            "iceberg order",
            "market cap",
            "market capitalization",
            "volume",
            "liquidity",
            "volatility",
            "order book",
            "depth",
            "spread",
            "bid",
            "ask",
            "slippage",
            "risk management",
            "position sizing",
            "leverage",
            "margin",
            "liquidation",
            "stop loss",
            "take profit",
            "risk reward ratio",
            "drawdown",
            "satoshi",
            "sats",
            "halving",
            "halving event",
            "difficulty adjustment",
            "hash rate",
            "mining",
            "miner",
            "pool",
            "block reward",
            "fear and greed",
            "fomo",
            "fear of missing out",
            "bear market",
            "bull market",
            "accumulation",
            "distribution",
            "capitulation",
            "euphoria",
            "panic",
            "fundamental analysis",
            "technical analysis",
            "on-chain analysis",
            "sentiment analysis",
            "price action",
            "chart analysis",
            "exchange",
            "binance",
            "coinbase",
            "kraken",
            "bitfinex",
            "futures",
            "perpetual",
            "options",
            "spot",
            "margin",
            "timeframe",
            "1m",
            "5m",
            "15m",
            "1h",
            "4h",
            "1d",
            "1w",
            "1M",
            "candle",
            "candlestick",
            "timeframe analysis",
        ],
        "entity_types": [
            "TechnicalIndicator",
            "ChartPattern",
            "TradingStrategy",
            "MarketCondition",
            "SupportLevel",
            "ResistanceLevel",
            "TradingSignal",
            "RiskManagementRule",
            "TradingSession",
            "OrderType",
            "Exchange",
            "MarketEvent",
        ],
        "relationship_types": [
            "INDICATES",
            "PRECEDES",
            "FOLLOWS",
            "CONFIRMS",
            "REJECTS",
            "PART_OF",
            "GENERATES",
            "REQUIRES",
            "INFLUENCES",
            "CORRELATES_WITH",
        ],
        "extraction_goals": [
            "Identify technical indicators mentioned in the text",
            "Extract chart patterns and their characteristics",
            "Find trading strategies and their components",
            "Detect market conditions and sentiment",
            "Identify support and resistance levels",
            "Extract risk management rules and parameters",
            "Find trading signals and their confidence levels",
            "Identify exchanges and platforms mentioned",
            "Extract order types and their parameters",
            "Find market events and their impact",
        ],
    },
}
