// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-fetch";
import type {
  HealthCheckHealthGetError,
  HealthCheckHealthGetResponse,
  ReadinessCheckReadyGetError,
  ReadinessCheckReadyGetResponse,
  TranslateQueryApiV1QueryTranslatePostData,
  TranslateQueryApiV1QueryTranslatePostError,
  TranslateQueryApiV1QueryTranslatePostResponse,
  ExecuteQueryApiV1QueryExecutePostData,
  ExecuteQueryApiV1QueryExecutePostError,
  ExecuteQueryApiV1QueryExecutePostResponse,
  GetSchemaApiV1QuerySchemaGetError,
  GetSchemaApiV1QuerySchemaGetResponse,
  GetPendingReviewsApiV1ReviewPendingGetData,
  GetPendingReviewsApiV1ReviewPendingGetError,
  GetPendingReviewsApiV1ReviewPendingGetResponse,
  GetReviewApiV1ReviewReviewIdGetData,
  GetReviewApiV1ReviewReviewIdGetError,
  GetReviewApiV1ReviewReviewIdGetResponse,
  ApproveReviewApiV1ReviewReviewIdApprovePostData,
  ApproveReviewApiV1ReviewReviewIdApprovePostError,
  ApproveReviewApiV1ReviewReviewIdApprovePostResponse,
  RejectReviewApiV1ReviewReviewIdRejectPostData,
  RejectReviewApiV1ReviewReviewIdRejectPostError,
  RejectReviewApiV1ReviewReviewIdRejectPostResponse,
  GetGraphSummaryApiV1GraphsGraphIdSummaryGetData,
  GetGraphSummaryApiV1GraphsGraphIdSummaryGetError,
  GetGraphSummaryApiV1GraphsGraphIdSummaryGetResponse,
  GetNeighborhoodApiV1GraphsGraphIdNodesNodeIdNeighborhoodGetData,
  GetNeighborhoodApiV1GraphsGraphIdNodesNodeIdNeighborhoodGetError,
  GetNeighborhoodApiV1GraphsGraphIdNodesNodeIdNeighborhoodGetResponse,
  FindPathApiV1GraphsGraphIdFindPathPostData,
  FindPathApiV1GraphsGraphIdFindPathPostError,
  FindPathApiV1GraphsGraphIdFindPathPostResponse,
  ExportGraphApiV1GraphsGraphIdExportGetData,
  ExportGraphApiV1GraphsGraphIdExportGetError,
  ExportGraphApiV1GraphsGraphIdExportGetResponse,
  GetDocumentApiV1DocumentsDocumentIdGetData,
  GetDocumentApiV1DocumentsDocumentIdGetError,
  GetDocumentApiV1DocumentsDocumentIdGetResponse,
  GetDocumentContentApiV1DocumentsDocumentIdContentGetData,
  GetDocumentContentApiV1DocumentsDocumentIdContentGetError,
  GetDocumentContentApiV1DocumentsDocumentIdContentGetResponse,
  GetDocumentSpansApiV1DocumentsDocumentIdSpansGetData,
  GetDocumentSpansApiV1DocumentsDocumentIdSpansGetError,
  GetDocumentSpansApiV1DocumentsDocumentIdSpansGetResponse,
  GetDocumentEntitiesApiV1DocumentsDocumentIdEntitiesGetData,
  GetDocumentEntitiesApiV1DocumentsDocumentIdEntitiesGetError,
  GetDocumentEntitiesApiV1DocumentsDocumentIdEntitiesGetResponse,
  SearchDocumentsApiV1DocumentsSearchPostData,
  SearchDocumentsApiV1DocumentsSearchPostError,
  SearchDocumentsApiV1DocumentsSearchPostResponse,
  CreateAnnotationApiV1DocumentsDocumentIdAnnotationsPostData,
  CreateAnnotationApiV1DocumentsDocumentIdAnnotationsPostError,
  CreateAnnotationApiV1DocumentsDocumentIdAnnotationsPostResponse,
  GetOpenapiApiV1OpenapiGetError,
  GetOpenapiApiV1OpenapiGetResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Health Check
 * Health check endpoint for monitoring and load balancers.
 *
 * Returns:
 * Basic service health information
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    HealthCheckHealthGetResponse,
    HealthCheckHealthGetError,
    ThrowOnError
  >({
    ...options,
    url: "/health",
  });
};

/**
 * Readiness Check
 * Readiness check endpoint for Kubernetes deployments.
 *
 * Returns:
 * Service readiness status
 */
export const readinessCheckReadyGet = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadinessCheckReadyGetResponse,
    ReadinessCheckReadyGetError,
    ThrowOnError
  >({
    ...options,
    url: "/ready",
  });
};

/**
 * Translate Query
 * Translate natural language query to SQL without executing it.
 *
 * Args:
 * nl_query: Natural language query string.
 * agent: TextToSQLAgent instance (injected by dependency).
 *
 * Returns:
 * Dictionary containing:
 * - sql: The generated SQL statement
 * - warnings: List of validation warnings
 * - error: Error message (if any)
 */
export const translateQueryApiV1QueryTranslatePost = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    TranslateQueryApiV1QueryTranslatePostData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    TranslateQueryApiV1QueryTranslatePostResponse,
    TranslateQueryApiV1QueryTranslatePostError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/query/translate",
  });
};

/**
 * Execute Query
 * Translate and execute natural language query.
 *
 * Args:
 * nl_query: Natural language query string.
 * agent: TextToSQLAgent instance (injected by dependency).
 *
 * Returns:
 * Dictionary containing:
 * - sql: The generated SQL statement
 * - results: Query results (if successful)
 * - warnings: List of validation warnings
 * - error: Error message (if any)
 */
export const executeQueryApiV1QueryExecutePost = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    ExecuteQueryApiV1QueryExecutePostData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    ExecuteQueryApiV1QueryExecutePostResponse,
    ExecuteQueryApiV1QueryExecutePostError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/query/execute",
  });
};

/**
 * Get Schema
 * Get database schema information.
 *
 * Args:
 * agent: TextToSQLAgent instance (injected by dependency).
 *
 * Returns:
 * Dictionary containing table names and their columns with data types.
 */
export const getSchemaApiV1QuerySchemaGet = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetSchemaApiV1QuerySchemaGetResponse,
    GetSchemaApiV1QuerySchemaGetError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/query/schema",
  });
};

/**
 * Get Pending Reviews
 * Get pending reviews ordered by priority.
 *
 * Args:
 * limit: Maximum number of reviews to return (default: 50)
 * offset: Number of reviews to skip (default: 0)
 * db: Database session dependency
 *
 * Returns:
 * List of pending review items
 */
export const getPendingReviewsApiV1ReviewPendingGet = <
  ThrowOnError extends boolean = false,
>(
  options?: OptionsLegacyParser<
    GetPendingReviewsApiV1ReviewPendingGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    GetPendingReviewsApiV1ReviewPendingGetResponse,
    GetPendingReviewsApiV1ReviewPendingGetError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/review/pending",
  });
};

/**
 * Get Review
 * Get a specific review by ID.
 *
 * Args:
 * review_id: ID of the review to retrieve
 * db: Database session dependency
 *
 * Returns:
 * Review item
 *
 * Raises:
 * HTTPException: If review not found
 */
export const getReviewApiV1ReviewReviewIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    GetReviewApiV1ReviewReviewIdGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    GetReviewApiV1ReviewReviewIdGetResponse,
    GetReviewApiV1ReviewReviewIdGetError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/review/{review_id}",
  });
};

/**
 * Approve Review
 * Approve a review.
 *
 * Args:
 * review_id: ID of the review to approve
 * approval: Approval data including optional reviewer notes
 * db: Database session dependency
 *
 * Returns:
 * True if review was approved
 *
 * Raises:
 * HTTPException: If review not found
 */
export const approveReviewApiV1ReviewReviewIdApprovePost = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    ApproveReviewApiV1ReviewReviewIdApprovePostData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    ApproveReviewApiV1ReviewReviewIdApprovePostResponse,
    ApproveReviewApiV1ReviewReviewIdApprovePostError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/review/{review_id}/approve",
  });
};

/**
 * Reject Review
 * Reject a review with corrections.
 *
 * Args:
 * review_id: ID of the review to reject
 * rejection: Rejection data including corrections and optional reviewer notes
 * db: Database session dependency
 *
 * Returns:
 * True if review was rejected and corrections applied
 *
 * Raises:
 * HTTPException: If review not found
 */
export const rejectReviewApiV1ReviewReviewIdRejectPost = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    RejectReviewApiV1ReviewReviewIdRejectPostData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    RejectReviewApiV1ReviewReviewIdRejectPostResponse,
    RejectReviewApiV1ReviewReviewIdRejectPostError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/review/{review_id}/reject",
  });
};

/**
 * Get Graph Summary
 * GET /api/v1/graphs/{graph_id}:summary
 *
 * Returns community-level graph overview for Sigma.js initial view.
 * Uses Map-Reduce style aggregation to efficiently calculate inter-community edges.
 *
 * AIP-136 Custom Method pattern for operations that don't fit standard CRUD.
 */
export const getGraphSummaryApiV1GraphsGraphIdSummaryGet = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    GetGraphSummaryApiV1GraphsGraphIdSummaryGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    GetGraphSummaryApiV1GraphsGraphIdSummaryGetResponse,
    GetGraphSummaryApiV1GraphsGraphIdSummaryGetError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/graphs/{graph_id}:summary",
  });
};

/**
 * Get Neighborhood
 * GET /api/v1/graphs/{graph_id}/nodes/{node_id}:neighborhood
 *
 * Expand entity neighborhood for Sigma.js drill-down interactions.
 * Returns immediate neighbors and connecting edges with confidence filtering.
 *
 * AIP-136 Custom Method pattern for complex graph operations.
 */
export const getNeighborhoodApiV1GraphsGraphIdNodesNodeIdNeighborhoodGet = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    GetNeighborhoodApiV1GraphsGraphIdNodesNodeIdNeighborhoodGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    GetNeighborhoodApiV1GraphsGraphIdNodesNodeIdNeighborhoodGetResponse,
    GetNeighborhoodApiV1GraphsGraphIdNodesNodeIdNeighborhoodGetError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/graphs/{graph_id}/nodes/{node_id}:neighborhood",
  });
};

/**
 * Find Path
 * POST /api/v1/graphs/{graph_id}:findPath
 *
 * Find paths between two nodes using various algorithms.
 * Server-side path finding avoids moving large datasets to client.
 *
 * AIP-136 Custom Method for complex graph analytics.
 */
export const findPathApiV1GraphsGraphIdFindPathPost = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    FindPathApiV1GraphsGraphIdFindPathPostData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    FindPathApiV1GraphsGraphIdFindPathPostResponse,
    FindPathApiV1GraphsGraphIdFindPathPostError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/graphs/{graph_id}:findPath",
  });
};

/**
 * Export Graph
 * GET /api/v1/graphs/{graph_id}:export
 *
 * Export graph in Graphology JSON format for Sigma.js compatibility.
 * Can include pre-calculated layout coordinates for large graphs.
 *
 * AIP-136 Custom Method for data export operations.
 */
export const exportGraphApiV1GraphsGraphIdExportGet = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    ExportGraphApiV1GraphsGraphIdExportGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    ExportGraphApiV1GraphsGraphIdExportGetResponse,
    ExportGraphApiV1GraphsGraphIdExportGetError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/graphs/{graph_id}:export",
  });
};

/**
 * Get Document
 * GET /api/v1/documents/{document_id}
 *
 * Get document metadata and extraction statistics.
 * AIP-131 Get method for retrieving resource by ID.
 */
export const getDocumentApiV1DocumentsDocumentIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    GetDocumentApiV1DocumentsDocumentIdGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    GetDocumentApiV1DocumentsDocumentIdGetResponse,
    GetDocumentApiV1DocumentsDocumentIdGetError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/documents/{document_id}",
  });
};

/**
 * Get Document Content
 * GET /api/v1/documents/{document_id}/content
 *
 * Get document content with all chunks concatenated in order.
 * Supports content extraction state and metadata.
 */
export const getDocumentContentApiV1DocumentsDocumentIdContentGet = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    GetDocumentContentApiV1DocumentsDocumentIdContentGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    GetDocumentContentApiV1DocumentsDocumentIdContentGetResponse,
    GetDocumentContentApiV1DocumentsDocumentIdContentGetError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/documents/{document_id}/content",
  });
};

/**
 * Get Document Spans
 * GET /api/v1/documents/{document_id}/spans
 *
 * Get all text spans with entity references for exact text highlighting.
 * Calculates absolute character offsets using the OffsetCalculationService.
 *
 * Critical for "Click entity -> See text evidence" functionality.
 * Implements W3C Web Annotation Data Model compliance.
 */
export const getDocumentSpansApiV1DocumentsDocumentIdSpansGet = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    GetDocumentSpansApiV1DocumentsDocumentIdSpansGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    GetDocumentSpansApiV1DocumentsDocumentIdSpansGetResponse,
    GetDocumentSpansApiV1DocumentsDocumentIdSpansGetError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/documents/{document_id}/spans",
  });
};

/**
 * Get Document Entities
 * GET /api/v1/documents/{document_id}/entities
 *
 * Get all entities extracted from document with their locations and confidence scores.
 * Groups multiple occurrences of the same entity.
 */
export const getDocumentEntitiesApiV1DocumentsDocumentIdEntitiesGet = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    GetDocumentEntitiesApiV1DocumentsDocumentIdEntitiesGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    GetDocumentEntitiesApiV1DocumentsDocumentIdEntitiesGetResponse,
    GetDocumentEntitiesApiV1DocumentsDocumentIdEntitiesGetError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/documents/{document_id}/entities",
  });
};

/**
 * Search Documents
 * POST /api/v1/documents:search
 *
 * Hybrid search combining vector similarity (semantic) and keyword search.
 * Uses Reciprocal Rank Fusion for result merging with weights:
 * - Vector search: 0.7 weight (semantic meaning)
 * - Keyword search: 0.3 weight (exact matches)
 *
 * AIP-136 Custom Method for search operations.
 */
export const searchDocumentsApiV1DocumentsSearchPost = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    SearchDocumentsApiV1DocumentsSearchPostData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    SearchDocumentsApiV1DocumentsSearchPostResponse,
    SearchDocumentsApiV1DocumentsSearchPostError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/documents/:search",
  });
};

/**
 * Create Annotation
 * POST /api/v1/documents/{document_id}/annotations
 *
 * Create a W3C Web Annotation for a document excerpt.
 * Supports both TextPositionSelector and TextQuoteSelector.
 *
 * AIP-136 Custom Method for creating annotations.
 */
export const createAnnotationApiV1DocumentsDocumentIdAnnotationsPost = <
  ThrowOnError extends boolean = false,
>(
  options: OptionsLegacyParser<
    CreateAnnotationApiV1DocumentsDocumentIdAnnotationsPostData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    CreateAnnotationApiV1DocumentsDocumentIdAnnotationsPostResponse,
    CreateAnnotationApiV1DocumentsDocumentIdAnnotationsPostError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/documents/{document_id}/annotations",
  });
};

/**
 * Get Openapi
 * Alternative OpenAPI endpoint for better client generation.
 *
 * Returns:
 * Complete OpenAPI specification
 */
export const getOpenapiApiV1OpenapiGet = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetOpenapiApiV1OpenapiGetResponse,
    GetOpenapiApiV1OpenapiGetError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/openapi",
  });
};
