// This file is auto-generated by @hey-api/openapi-ts

/**
 * AIP-193 compliant error structure.
 */
export type APIError = {
  /**
   * HTTP status code
   */
  code: number;
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * google.rpc.Code enum value (e.g., NOT_FOUND)
   */
  status: string;
  /**
   * Detailed error information
   */
  details?: Array<ErrorInfo>;
};

export type APIResponse_DocumentContentResponse_ = {
  /**
   * Indicates if request succeeded
   */
  success: boolean;
  /**
   * Response payload on success
   */
  data?: DocumentContentResponse | null;
  /**
   * Error details on failure
   */
  error?: APIError | null;
  /**
   * Additional metadata (pagination, timing, request_id)
   */
  metadata?: {
    [key: string]: unknown;
  } | null;
};

export type APIResponse_DocumentEntitiesResponse_ = {
  /**
   * Indicates if request succeeded
   */
  success: boolean;
  /**
   * Response payload on success
   */
  data?: DocumentEntitiesResponse | null;
  /**
   * Error details on failure
   */
  error?: APIError | null;
  /**
   * Additional metadata (pagination, timing, request_id)
   */
  metadata?: {
    [key: string]: unknown;
  } | null;
};

export type APIResponse_DocumentResponse_ = {
  /**
   * Indicates if request succeeded
   */
  success: boolean;
  /**
   * Response payload on success
   */
  data?: DocumentResponse | null;
  /**
   * Error details on failure
   */
  error?: APIError | null;
  /**
   * Additional metadata (pagination, timing, request_id)
   */
  metadata?: {
    [key: string]: unknown;
  } | null;
};

export type APIResponse_DocumentSearchResponse_ = {
  /**
   * Indicates if request succeeded
   */
  success: boolean;
  /**
   * Response payload on success
   */
  data?: DocumentSearchResponse | null;
  /**
   * Error details on failure
   */
  error?: APIError | null;
  /**
   * Additional metadata (pagination, timing, request_id)
   */
  metadata?: {
    [key: string]: unknown;
  } | null;
};

export type APIResponse_DocumentSpansResponse_ = {
  /**
   * Indicates if request succeeded
   */
  success: boolean;
  /**
   * Response payload on success
   */
  data?: DocumentSpansResponse | null;
  /**
   * Error details on failure
   */
  error?: APIError | null;
  /**
   * Additional metadata (pagination, timing, request_id)
   */
  metadata?: {
    [key: string]: unknown;
  } | null;
};

export type APIResponse_W3CAnnotation_ = {
  /**
   * Indicates if request succeeded
   */
  success: boolean;
  /**
   * Response payload on success
   */
  data?: W3CAnnotation | null;
  /**
   * Error details on failure
   */
  error?: APIError | null;
  /**
   * Additional metadata (pagination, timing, request_id)
   */
  metadata?: {
    [key: string]: unknown;
  } | null;
};

/**
 * Document content with text and extraction information.
 */
export type DocumentContentResponse = {
  document_id: string;
  content: string;
  mime_type: string;
  metadata: {
    [key: string]: unknown;
  };
  extraction_state: {
    [key: string]: unknown;
  };
  total_length: number;
  chunk_count: number;
};

/**
 * All entities extracted from document.
 */
export type DocumentEntitiesResponse = {
  document_id: string;
  entities: Array<DocumentEntityResponse>;
  total: number;
  domain: string | null;
};

/**
 * Entity extracted from document with location information.
 */
export type DocumentEntityResponse = {
  entity_id: string;
  name: string;
  entity_type: string;
  description: string | null;
  confidence: number;
  properties: {
    [key: string]: unknown;
  };
  spans: Array<{
    [key: string]: unknown;
  }>;
  first_mentioned: string | null;
};

/**
 * Document metadata response.
 */
export type DocumentResponse = {
  id: string;
  name: string;
  source_uri: string | null;
  status: string;
  domain: string | null;
  metadata: {
    [key: string]: unknown;
  };
  created_at: string;
  updated_at: string;
  chunk_count: number;
  entity_count: number;
  processing_time_ms: number | null;
};

/**
 * Request for hybrid search across documents.
 */
export type DocumentSearchRequest = {
  /**
   * Search query text
   */
  query: string;
  /**
   * Search type to use
   */
  search_type?: string;
  /**
   * Filter by domains
   */
  domains?: Array<string> | null;
  /**
   * Start date filter
   */
  date_from?: string | null;
  /**
   * End date filter
   */
  date_to?: string | null;
  /**
   * Filter by entity types
   */
  entity_types?: Array<string> | null;
  /**
   * Minimum confidence
   */
  min_confidence?: number;
  /**
   * Maximum results
   */
  limit?: number;
  /**
   * Result offset
   */
  offset?: number;
};

/**
 * Hybrid search response with ranked results.
 */
export type DocumentSearchResponse = {
  results: Array<SearchResult>;
  total: number;
  query: string;
  took_ms: number;
  search_type: string;
};

/**
 * All text spans with entity references for highlighting.
 */
export type DocumentSpansResponse = {
  document_id: string;
  spans: Array<{
    [key: string]: unknown;
  }>;
  total_spans: number;
  verified_spans: number;
  entities_found: number;
  coverage_percentage: number;
};

/**
 * Detailed error information following google.rpc.ErrorInfo pattern.
 */
export type ErrorInfo = {
  /**
   * Error reason code
   */
  reason: string;
  /**
   * Error domain identifier
   */
  domain?: string;
  /**
   * Additional error context
   */
  metadata?: {
    [key: string]: string;
  };
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

/**
 * Single search result with relevance information.
 */
export type SearchResult = {
  document_id: string;
  chunk_id: string;
  /**
   * Relevance score
   */
  score: number;
  /**
   * Matching text snippet
   */
  snippet: string;
  /**
   * Highlight regions
   */
  highlights: Array<{
    [key: string]: unknown;
  }>;
  /**
   * Matched entities
   */
  entities: Array<{
    [key: string]: unknown;
  }>;
  metadata: {
    [key: string]: unknown;
  };
  match_type: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

/**
 * W3C Web Annotation Data Model.
 */
export type W3CAnnotation = {
  id?: string | null;
  type?: string;
  /**
   * Target with selectors
   */
  target: {
    [key: string]: unknown;
  };
  /**
   * Annotation body/content
   */
  body: {
    [key: string]: unknown;
  };
  created?: string | null;
  creator?: string | null;
  motivation?: string | null;
};
