"""add_vector_indexes

Revision ID: b20e59aa81e1
Revises: 
Create Date: 2026-01-28 23:12:37.430986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b20e59aa81e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_domain_schema_level'), table_name='domain_schemas')
    op.drop_index(op.f('idx_domain_schema_parent'), table_name='domain_schemas')
    op.drop_index(op.f('ix_domain_schemas_domain_name'), table_name='domain_schemas')
    op.drop_index(op.f('ix_domain_schemas_parent_domain_id'), table_name='domain_schemas')
    op.drop_table('domain_schemas')
    op.drop_index(op.f('idx_chunk_embedding'), table_name='chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_chunk_embedding_ivfflat', 'chunks', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('idx_entity_embedding'), table_name='entities', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_entity_embedding_ivfflat', 'entities', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_entity_embedding_ivfflat', table_name='entities', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('idx_entity_embedding'), 'entities', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_chunk_embedding_ivfflat', table_name='chunks', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('idx_chunk_embedding'), 'chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_table('domain_schemas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('domain_display_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parent_domain_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('domain_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('inheritance_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_types', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('validation_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_domain_id'], ['domain_schemas.id'], name=op.f('domain_schemas_parent_domain_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('domain_schemas_pkey'))
    )
    op.create_index(op.f('ix_domain_schemas_parent_domain_id'), 'domain_schemas', ['parent_domain_id'], unique=False)
    op.create_index(op.f('ix_domain_schemas_domain_name'), 'domain_schemas', ['domain_name'], unique=True)
    op.create_index(op.f('idx_domain_schema_parent'), 'domain_schemas', ['parent_domain_id'], unique=False)
    op.create_index(op.f('idx_domain_schema_level'), 'domain_schemas', ['domain_level'], unique=False)
    # ### end Alembic commands ###
